// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.cy.netty.entity.proto;

public final class CommonHead {
  private CommonHead() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseHeadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmd = 1;
    /**
     * <code>required int32 cmd = 1;</code>
     *
     * <pre>
     *返回的命令号
     * </pre>
     */
    boolean hasCmd();
    /**
     * <code>required int32 cmd = 1;</code>
     *
     * <pre>
     *返回的命令号
     * </pre>
     */
    int getCmd();

    // optional int32 errCode = 2;
    /**
     * <code>optional int32 errCode = 2;</code>
     *
     * <pre>
     *状态码 &lt;0位异常 =0为正常请求成功
     * </pre>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 2;</code>
     *
     * <pre>
     *状态码 &lt;0位异常 =0为正常请求成功
     * </pre>
     */
    int getErrCode();

    // optional string err = 3;
    /**
     * <code>optional string err = 3;</code>
     *
     * <pre>
     *错误的内容
     * </pre>
     */
    boolean hasErr();
    /**
     * <code>optional string err = 3;</code>
     *
     * <pre>
     *错误的内容
     * </pre>
     */
    java.lang.String getErr();
    /**
     * <code>optional string err = 3;</code>
     *
     * <pre>
     *错误的内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrBytes();

    // optional int32 requestCmd = 4;
    /**
     * <code>optional int32 requestCmd = 4;</code>
     *
     * <pre>
     *请求的命令号
     * </pre>
     */
    boolean hasRequestCmd();
    /**
     * <code>optional int32 requestCmd = 4;</code>
     *
     * <pre>
     *请求的命令号
     * </pre>
     */
    int getRequestCmd();
  }
  /**
   * Protobuf type {@code dynasty.ResponseHead}
   *
   * <pre>
   *响应头文件，请求时不需要，只需要有cmd，发生异常时cmd=1，消息内容如下
   * </pre>
   */
  public static final class ResponseHead extends
      com.google.protobuf.GeneratedMessage
      implements ResponseHeadOrBuilder {
    // Use ResponseHead.newBuilder() to construct.
    private ResponseHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseHead(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseHead defaultInstance;
    public static ResponseHead getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseHead getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errCode_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              err_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              requestCmd_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_ResponseHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_ResponseHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cy.netty.entity.proto.CommonHead.ResponseHead.class, com.cy.netty.entity.proto.CommonHead.ResponseHead.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseHead> PARSER =
        new com.google.protobuf.AbstractParser<ResponseHead>() {
      public ResponseHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseHead(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseHead> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>required int32 cmd = 1;</code>
     *
     * <pre>
     *返回的命令号
     * </pre>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmd = 1;</code>
     *
     * <pre>
     *返回的命令号
     * </pre>
     */
    public int getCmd() {
      return cmd_;
    }

    // optional int32 errCode = 2;
    public static final int ERRCODE_FIELD_NUMBER = 2;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 2;</code>
     *
     * <pre>
     *状态码 &lt;0位异常 =0为正常请求成功
     * </pre>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 errCode = 2;</code>
     *
     * <pre>
     *状态码 &lt;0位异常 =0为正常请求成功
     * </pre>
     */
    public int getErrCode() {
      return errCode_;
    }

    // optional string err = 3;
    public static final int ERR_FIELD_NUMBER = 3;
    private java.lang.Object err_;
    /**
     * <code>optional string err = 3;</code>
     *
     * <pre>
     *错误的内容
     * </pre>
     */
    public boolean hasErr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string err = 3;</code>
     *
     * <pre>
     *错误的内容
     * </pre>
     */
    public java.lang.String getErr() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          err_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string err = 3;</code>
     *
     * <pre>
     *错误的内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrBytes() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        err_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 requestCmd = 4;
    public static final int REQUESTCMD_FIELD_NUMBER = 4;
    private int requestCmd_;
    /**
     * <code>optional int32 requestCmd = 4;</code>
     *
     * <pre>
     *请求的命令号
     * </pre>
     */
    public boolean hasRequestCmd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 requestCmd = 4;</code>
     *
     * <pre>
     *请求的命令号
     * </pre>
     */
    public int getRequestCmd() {
      return requestCmd_;
    }

    private void initFields() {
      cmd_ = 0;
      errCode_ = 0;
      err_ = "";
      requestCmd_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, requestCmd_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, requestCmd_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.ResponseHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cy.netty.entity.proto.CommonHead.ResponseHead prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dynasty.ResponseHead}
     *
     * <pre>
     *响应头文件，请求时不需要，只需要有cmd，发生异常时cmd=1，消息内容如下
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cy.netty.entity.proto.CommonHead.ResponseHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_ResponseHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_ResponseHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cy.netty.entity.proto.CommonHead.ResponseHead.class, com.cy.netty.entity.proto.CommonHead.ResponseHead.Builder.class);
      }

      // Construct using com.cy.netty.entity.proto.CommonHead.ResponseHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        err_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        requestCmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_ResponseHead_descriptor;
      }

      public com.cy.netty.entity.proto.CommonHead.ResponseHead getDefaultInstanceForType() {
        return com.cy.netty.entity.proto.CommonHead.ResponseHead.getDefaultInstance();
      }

      public com.cy.netty.entity.proto.CommonHead.ResponseHead build() {
        com.cy.netty.entity.proto.CommonHead.ResponseHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cy.netty.entity.proto.CommonHead.ResponseHead buildPartial() {
        com.cy.netty.entity.proto.CommonHead.ResponseHead result = new com.cy.netty.entity.proto.CommonHead.ResponseHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.err_ = err_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestCmd_ = requestCmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cy.netty.entity.proto.CommonHead.ResponseHead) {
          return mergeFrom((com.cy.netty.entity.proto.CommonHead.ResponseHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cy.netty.entity.proto.CommonHead.ResponseHead other) {
        if (other == com.cy.netty.entity.proto.CommonHead.ResponseHead.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErr()) {
          bitField0_ |= 0x00000004;
          err_ = other.err_;
          onChanged();
        }
        if (other.hasRequestCmd()) {
          setRequestCmd(other.getRequestCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cy.netty.entity.proto.CommonHead.ResponseHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cy.netty.entity.proto.CommonHead.ResponseHead) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmd = 1;
      private int cmd_ ;
      /**
       * <code>required int32 cmd = 1;</code>
       *
       * <pre>
       *返回的命令号
       * </pre>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmd = 1;</code>
       *
       * <pre>
       *返回的命令号
       * </pre>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required int32 cmd = 1;</code>
       *
       * <pre>
       *返回的命令号
       * </pre>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmd = 1;</code>
       *
       * <pre>
       *返回的命令号
       * </pre>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // optional int32 errCode = 2;
      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 2;</code>
       *
       * <pre>
       *状态码 &lt;0位异常 =0为正常请求成功
       * </pre>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 errCode = 2;</code>
       *
       * <pre>
       *状态码 &lt;0位异常 =0为正常请求成功
       * </pre>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 2;</code>
       *
       * <pre>
       *状态码 &lt;0位异常 =0为正常请求成功
       * </pre>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000002;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 2;</code>
       *
       * <pre>
       *状态码 &lt;0位异常 =0为正常请求成功
       * </pre>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        onChanged();
        return this;
      }

      // optional string err = 3;
      private java.lang.Object err_ = "";
      /**
       * <code>optional string err = 3;</code>
       *
       * <pre>
       *错误的内容
       * </pre>
       */
      public boolean hasErr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string err = 3;</code>
       *
       * <pre>
       *错误的内容
       * </pre>
       */
      public java.lang.String getErr() {
        java.lang.Object ref = err_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          err_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string err = 3;</code>
       *
       * <pre>
       *错误的内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrBytes() {
        java.lang.Object ref = err_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          err_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string err = 3;</code>
       *
       * <pre>
       *错误的内容
       * </pre>
       */
      public Builder setErr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string err = 3;</code>
       *
       * <pre>
       *错误的内容
       * </pre>
       */
      public Builder clearErr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        err_ = getDefaultInstance().getErr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string err = 3;</code>
       *
       * <pre>
       *错误的内容
       * </pre>
       */
      public Builder setErrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        err_ = value;
        onChanged();
        return this;
      }

      // optional int32 requestCmd = 4;
      private int requestCmd_ ;
      /**
       * <code>optional int32 requestCmd = 4;</code>
       *
       * <pre>
       *请求的命令号
       * </pre>
       */
      public boolean hasRequestCmd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 requestCmd = 4;</code>
       *
       * <pre>
       *请求的命令号
       * </pre>
       */
      public int getRequestCmd() {
        return requestCmd_;
      }
      /**
       * <code>optional int32 requestCmd = 4;</code>
       *
       * <pre>
       *请求的命令号
       * </pre>
       */
      public Builder setRequestCmd(int value) {
        bitField0_ |= 0x00000008;
        requestCmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 requestCmd = 4;</code>
       *
       * <pre>
       *请求的命令号
       * </pre>
       */
      public Builder clearRequestCmd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestCmd_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dynasty.ResponseHead)
    }

    static {
      defaultInstance = new ResponseHead(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dynasty.ResponseHead)
  }

  public interface SyncStatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // required int32 stat = 2;
    /**
     * <code>required int32 stat = 2;</code>
     */
    boolean hasStat();
    /**
     * <code>required int32 stat = 2;</code>
     */
    int getStat();
  }
  /**
   * Protobuf type {@code dynasty.SyncStat}
   *
   * <pre>
   *同步请求标志,后台测试使用
   * </pre>
   */
  public static final class SyncStat extends
      com.google.protobuf.GeneratedMessage
      implements SyncStatOrBuilder {
    // Use SyncStat.newBuilder() to construct.
    private SyncStat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SyncStat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SyncStat defaultInstance;
    public static SyncStat getDefaultInstance() {
      return defaultInstance;
    }

    public SyncStat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SyncStat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stat_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_SyncStat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_SyncStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cy.netty.entity.proto.CommonHead.SyncStat.class, com.cy.netty.entity.proto.CommonHead.SyncStat.Builder.class);
    }

    public static com.google.protobuf.Parser<SyncStat> PARSER =
        new com.google.protobuf.AbstractParser<SyncStat>() {
      public SyncStat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncStat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SyncStat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // required int32 stat = 2;
    public static final int STAT_FIELD_NUMBER = 2;
    private int stat_;
    /**
     * <code>required int32 stat = 2;</code>
     */
    public boolean hasStat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 stat = 2;</code>
     */
    public int getStat() {
      return stat_;
    }

    private void initFields() {
      id_ = 0L;
      stat_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stat_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stat_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.SyncStat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cy.netty.entity.proto.CommonHead.SyncStat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dynasty.SyncStat}
     *
     * <pre>
     *同步请求标志,后台测试使用
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cy.netty.entity.proto.CommonHead.SyncStatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_SyncStat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_SyncStat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cy.netty.entity.proto.CommonHead.SyncStat.class, com.cy.netty.entity.proto.CommonHead.SyncStat.Builder.class);
      }

      // Construct using com.cy.netty.entity.proto.CommonHead.SyncStat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        stat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_SyncStat_descriptor;
      }

      public com.cy.netty.entity.proto.CommonHead.SyncStat getDefaultInstanceForType() {
        return com.cy.netty.entity.proto.CommonHead.SyncStat.getDefaultInstance();
      }

      public com.cy.netty.entity.proto.CommonHead.SyncStat build() {
        com.cy.netty.entity.proto.CommonHead.SyncStat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cy.netty.entity.proto.CommonHead.SyncStat buildPartial() {
        com.cy.netty.entity.proto.CommonHead.SyncStat result = new com.cy.netty.entity.proto.CommonHead.SyncStat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stat_ = stat_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cy.netty.entity.proto.CommonHead.SyncStat) {
          return mergeFrom((com.cy.netty.entity.proto.CommonHead.SyncStat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cy.netty.entity.proto.CommonHead.SyncStat other) {
        if (other == com.cy.netty.entity.proto.CommonHead.SyncStat.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStat()) {
          setStat(other.getStat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasStat()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cy.netty.entity.proto.CommonHead.SyncStat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cy.netty.entity.proto.CommonHead.SyncStat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required int32 stat = 2;
      private int stat_ ;
      /**
       * <code>required int32 stat = 2;</code>
       */
      public boolean hasStat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 stat = 2;</code>
       */
      public int getStat() {
        return stat_;
      }
      /**
       * <code>required int32 stat = 2;</code>
       */
      public Builder setStat(int value) {
        bitField0_ |= 0x00000002;
        stat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stat = 2;</code>
       */
      public Builder clearStat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stat_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dynasty.SyncStat)
    }

    static {
      defaultInstance = new SyncStat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dynasty.SyncStat)
  }

  public interface KeepAliveRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmd = 1 [default = 100000];
    /**
     * <code>required int32 cmd = 1 [default = 100000];</code>
     */
    boolean hasCmd();
    /**
     * <code>required int32 cmd = 1 [default = 100000];</code>
     */
    int getCmd();
  }
  /**
   * Protobuf type {@code dynasty.KeepAliveRequest}
   *
   * <pre>
   *100000心跳请求
   * </pre>
   */
  public static final class KeepAliveRequest extends
      com.google.protobuf.GeneratedMessage
      implements KeepAliveRequestOrBuilder {
    // Use KeepAliveRequest.newBuilder() to construct.
    private KeepAliveRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeepAliveRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeepAliveRequest defaultInstance;
    public static KeepAliveRequest getDefaultInstance() {
      return defaultInstance;
    }

    public KeepAliveRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeepAliveRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.class, com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<KeepAliveRequest> PARSER =
        new com.google.protobuf.AbstractParser<KeepAliveRequest>() {
      public KeepAliveRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeepAliveRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAliveRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmd = 1 [default = 100000];
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>required int32 cmd = 1 [default = 100000];</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmd = 1 [default = 100000];</code>
     */
    public int getCmd() {
      return cmd_;
    }

    private void initFields() {
      cmd_ = 100000;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cy.netty.entity.proto.CommonHead.KeepAliveRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dynasty.KeepAliveRequest}
     *
     * <pre>
     *100000心跳请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cy.netty.entity.proto.CommonHead.KeepAliveRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.class, com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.Builder.class);
      }

      // Construct using com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = 100000;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveRequest_descriptor;
      }

      public com.cy.netty.entity.proto.CommonHead.KeepAliveRequest getDefaultInstanceForType() {
        return com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.getDefaultInstance();
      }

      public com.cy.netty.entity.proto.CommonHead.KeepAliveRequest build() {
        com.cy.netty.entity.proto.CommonHead.KeepAliveRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cy.netty.entity.proto.CommonHead.KeepAliveRequest buildPartial() {
        com.cy.netty.entity.proto.CommonHead.KeepAliveRequest result = new com.cy.netty.entity.proto.CommonHead.KeepAliveRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cy.netty.entity.proto.CommonHead.KeepAliveRequest) {
          return mergeFrom((com.cy.netty.entity.proto.CommonHead.KeepAliveRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cy.netty.entity.proto.CommonHead.KeepAliveRequest other) {
        if (other == com.cy.netty.entity.proto.CommonHead.KeepAliveRequest.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cy.netty.entity.proto.CommonHead.KeepAliveRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cy.netty.entity.proto.CommonHead.KeepAliveRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmd = 1 [default = 100000];
      private int cmd_ = 100000;
      /**
       * <code>required int32 cmd = 1 [default = 100000];</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmd = 1 [default = 100000];</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required int32 cmd = 1 [default = 100000];</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmd = 1 [default = 100000];</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 100000;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dynasty.KeepAliveRequest)
    }

    static {
      defaultInstance = new KeepAliveRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dynasty.KeepAliveRequest)
  }

  public interface KeepAliveResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmd = 1 [default = 100001];
    /**
     * <code>required int32 cmd = 1 [default = 100001];</code>
     */
    boolean hasCmd();
    /**
     * <code>required int32 cmd = 1 [default = 100001];</code>
     */
    int getCmd();
  }
  /**
   * Protobuf type {@code dynasty.KeepAliveResponse}
   *
   * <pre>
   *100001心跳响应
   * </pre>
   */
  public static final class KeepAliveResponse extends
      com.google.protobuf.GeneratedMessage
      implements KeepAliveResponseOrBuilder {
    // Use KeepAliveResponse.newBuilder() to construct.
    private KeepAliveResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeepAliveResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeepAliveResponse defaultInstance;
    public static KeepAliveResponse getDefaultInstance() {
      return defaultInstance;
    }

    public KeepAliveResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeepAliveResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.class, com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<KeepAliveResponse> PARSER =
        new com.google.protobuf.AbstractParser<KeepAliveResponse>() {
      public KeepAliveResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeepAliveResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAliveResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmd = 1 [default = 100001];
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>required int32 cmd = 1 [default = 100001];</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmd = 1 [default = 100001];</code>
     */
    public int getCmd() {
      return cmd_;
    }

    private void initFields() {
      cmd_ = 100001;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cy.netty.entity.proto.CommonHead.KeepAliveResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dynasty.KeepAliveResponse}
     *
     * <pre>
     *100001心跳响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cy.netty.entity.proto.CommonHead.KeepAliveResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.class, com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.Builder.class);
      }

      // Construct using com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = 100001;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cy.netty.entity.proto.CommonHead.internal_static_dynasty_KeepAliveResponse_descriptor;
      }

      public com.cy.netty.entity.proto.CommonHead.KeepAliveResponse getDefaultInstanceForType() {
        return com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.getDefaultInstance();
      }

      public com.cy.netty.entity.proto.CommonHead.KeepAliveResponse build() {
        com.cy.netty.entity.proto.CommonHead.KeepAliveResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cy.netty.entity.proto.CommonHead.KeepAliveResponse buildPartial() {
        com.cy.netty.entity.proto.CommonHead.KeepAliveResponse result = new com.cy.netty.entity.proto.CommonHead.KeepAliveResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cy.netty.entity.proto.CommonHead.KeepAliveResponse) {
          return mergeFrom((com.cy.netty.entity.proto.CommonHead.KeepAliveResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cy.netty.entity.proto.CommonHead.KeepAliveResponse other) {
        if (other == com.cy.netty.entity.proto.CommonHead.KeepAliveResponse.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cy.netty.entity.proto.CommonHead.KeepAliveResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cy.netty.entity.proto.CommonHead.KeepAliveResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmd = 1 [default = 100001];
      private int cmd_ = 100001;
      /**
       * <code>required int32 cmd = 1 [default = 100001];</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmd = 1 [default = 100001];</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required int32 cmd = 1 [default = 100001];</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmd = 1 [default = 100001];</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 100001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dynasty.KeepAliveResponse)
    }

    static {
      defaultInstance = new KeepAliveResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dynasty.KeepAliveResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dynasty_ResponseHead_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dynasty_ResponseHead_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dynasty_SyncStat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dynasty_SyncStat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dynasty_KeepAliveRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dynasty_KeepAliveRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dynasty_KeepAliveResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dynasty_KeepAliveResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\007dynasty\"M\n\014ResponseHead\022" +
      "\013\n\003cmd\030\001 \002(\005\022\017\n\007errCode\030\002 \001(\005\022\013\n\003err\030\003 \001" +
      "(\t\022\022\n\nrequestCmd\030\004 \001(\005\"$\n\010SyncStat\022\n\n\002id" +
      "\030\001 \002(\003\022\014\n\004stat\030\002 \002(\005\"\'\n\020KeepAliveRequest" +
      "\022\023\n\003cmd\030\001 \002(\005:\006100000\"(\n\021KeepAliveRespon" +
      "se\022\023\n\003cmd\030\001 \002(\005:\006100001B\'\n\031com.cy.netty." +
      "entity.protoB\nCommonHead"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dynasty_ResponseHead_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dynasty_ResponseHead_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dynasty_ResponseHead_descriptor,
              new java.lang.String[] { "Cmd", "ErrCode", "Err", "RequestCmd", });
          internal_static_dynasty_SyncStat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_dynasty_SyncStat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dynasty_SyncStat_descriptor,
              new java.lang.String[] { "Id", "Stat", });
          internal_static_dynasty_KeepAliveRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_dynasty_KeepAliveRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dynasty_KeepAliveRequest_descriptor,
              new java.lang.String[] { "Cmd", });
          internal_static_dynasty_KeepAliveResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_dynasty_KeepAliveResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dynasty_KeepAliveResponse_descriptor,
              new java.lang.String[] { "Cmd", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
